// Common disposable / throwaway email domains. Not exhaustive but covers the
// frequently abused services.
const DISPOSABLE: ReadonlySet<string> = new Set([
  "mailinator.com", "mailinator.net", "mailinator2.com", "binkmail.com",
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmail.net", "tempmailo.com",
  "tempmail.dev", "tempmail.plus", "tmpmail.org", "tmpmail.net",
  "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minutemail.us",
  "20minutemail.com", "20minutemail.it", "30minutemail.com",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.biz",
  "guerrillamail.info", "guerrillamail.de", "grr.la", "sharklasers.com",
  "yopmail.com", "yopmail.fr", "yopmail.net", "cool.fr.nf", "jetable.fr.nf",
  "nospam.ze.tc", "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf",
  "trashmail.com", "trashmail.net", "trashmail.de", "trashmail.io", "trashmail.org",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "throwawaymail.com", "throwawaymail.net", "throwaway.email",
  "fakeinbox.com", "fake-mail.net", "fakemail.net", "fakemailgenerator.com",
  "getairmail.com", "getnada.com", "nada.email", "getairmail.gq",
  "maildrop.cc", "maildrop.gq", "spamgourmet.com", "spamgourmet.net",
  "spambox.us", "spam4.me", "spambog.com", "spambog.de", "spambog.ru",
  "mintemail.com", "mt2014.com", "mt2015.com", "thrott.com",
  "discard.email", "discardmail.com", "discardmail.de",
  "mailcatch.com", "mailnesia.com", "mailnull.com",
  "tempr.email", "tempemail.com", "tempemail.net", "tempemail.co.za",
  "emailondeck.com", "emailtemporanea.net", "mohmal.com",
  "burnermail.io", "burnermail.com", "anonbox.net",
  "dropmail.me", "harakirimail.com", "incognitomail.com", "incognitomail.org",
  "mailtemp.info", "fastacura.com", "fastchevy.com", "fastchrysler.com",
  "spam.la", "spamcero.com", "spamfree24.com", "spamfree24.de", "spamfree24.eu",
  "spamfree24.info", "spamfree24.net", "spamfree24.org", "spamhereplease.com",
  "spamherelots.com", "spamhole.com", "spaml.com", "spaml.de", "spammotel.com",
  "spamspot.com", "spamthis.co.uk", "speed.1s.fr", "supergreatmail.com",
  "trbvm.com", "trbvn.com", "trbvo.com", "tyldd.com", "veryrealemail.com",
  "vinbazar.com", "vipmail.name", "wakingupesther.com", "walkmail.net",
  "webemail.me", "webtrip.ch", "webuser.in", "wee.my", "wegwerf-email-addressen.de",
  "wegwerf-emails.de", "wegwerfadresse.de", "wegwerfemail.com", "wegwerfemail.de",
  "wetrainbayarea.com", "wetrainbayarea.org", "whatpaas.com", "whyspam.me",
  "willhackforfood.biz", "willselfdestruct.com", "winemaven.info",
  "wronghead.com", "wuzup.net", "wuzupmail.net", "xagloo.com", "xemaps.com",
  "xents.com", "xmaily.com", "xoxy.net", "yapped.net", "yeah.net",
  "yourdomain.com", "ypmail.webarnak.fr.eu.org", "zehnminuten.de",
  "zehnminutenmail.de", "zetmail.com", "zippymail.info", "zoaxe.com",
  "zoemail.org", "zomg.info", "zxcv.com", "zxcvbnm.com", "zzz.com",
  "moakt.com", "moakt.cc", "moakt.ws", "tmail.ws", "bccto.me", "tafmail.com",
  "20email.eu", "anonaddy.me", "anonaddy.com",
  "simplelogin.io", "slmail.me", "8alias.com", "0wnd.net", "0wnd.org",
]);

export function isDisposableDomain(domain: string): boolean {
  return DISPOSABLE.has(domain.toLowerCase());
}
