/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApartamentaiRouteImport } from './routes/apartamentai'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BanketineSaleRouteImport } from './routes/banketine-sale'
import { Route as DovanuKuponaiRouteImport } from './routes/dovanu-kuponai'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as NamelisRouteImport } from './routes/namelis'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RestobarasRouteImport } from './routes/restobaras'
import { Route as SaunaRouteImport } from './routes/sauna'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as ApartamentaiIndexRouteImport } from './routes/apartamentai.index'
import { Route as ApartamentaiPropertyIdRouteImport } from './routes/apartamentai.$propertyId'
import { Route as ApartamentaiStandartiniaiRouteImport } from './routes/apartamentai.standartiniai'
import { Route as ApartamentaiSuTerasaRouteImport } from './routes/apartamentai.su-terasa'
import { Route as ApieIndexRouteImport } from './routes/apie.index'
import { Route as ApieTaisyklesRouteImport } from './routes/apie.taisykles'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnApartamentaiRouteImport } from './routes/en/apartamentai'
import { Route as EnApieRouteImport } from './routes/en/apie'
import { Route as EnBanketineSaleRouteImport } from './routes/en/banketine-sale'
import { Route as EnDovanuKuponaiRouteImport } from './routes/en/dovanu-kuponai'
import { Route as EnKontaktaiRouteImport } from './routes/en/kontaktai'
import { Route as EnNamelisRouteImport } from './routes/en/namelis'
import { Route as EnPrivatumoPolitikaRouteImport } from './routes/en/privatumo-politika'
import { Route as EnRestobarasRouteImport } from './routes/en/restobaras'
import { Route as EnSaunaRouteImport } from './routes/en/sauna'
import { Route as EnTaisyklesRouteImport } from './routes/en/taisykles'
import { Route as RezervacijaPatvirtintaRouteImport } from './routes/rezervacija.patvirtinta'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminHousekeepingRouteImport } from './routes/_authenticated/admin.housekeeping'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as ApartamentaiTipasCategorySlugRouteImport } from './routes/apartamentai.tipas.$categorySlug'
import { Route as ApiPublicIcalSyncRouteImport } from './routes/api/public/ical-sync'
import { Route as ApiPublicNotificationsCronRouteImport } from './routes/api/public/notifications-cron'
import { Route as EnApartamentaiIndexRouteImport } from './routes/en/apartamentai.index'
import { Route as EnApartamentaiPropertyIdRouteImport } from './routes/en/apartamentai.$propertyId'
import { Route as EnApartamentaiStandartiniaiRouteImport } from './routes/en/apartamentai.standartiniai'
import { Route as EnApartamentaiSuTerasaRouteImport } from './routes/en/apartamentai.su-terasa'
import { Route as EnApieIndexRouteImport } from './routes/en/apie.index'
import { Route as EnApieTaisyklesRouteImport } from './routes/en/apie.taisykles'
import { Route as EnRezervacijaPatvirtintaRouteImport } from './routes/en/rezervacija.patvirtinta'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin.bookings.index'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'
import { Route as AuthenticatedAdminBookingsNewRouteImport } from './routes/_authenticated/admin.bookings.new'
import { Route as AuthenticatedAdminPropertiesIndexRouteImport } from './routes/_authenticated/admin.properties.index'
import { Route as AuthenticatedAdminPropertiesNewRouteImport } from './routes/_authenticated/admin.properties.new'
import { Route as ApiPublicV1AvailabilityRouteImport } from './routes/api/public/v1/availability'
import { Route as ApiPublicV1BookingsRouteImport } from './routes/api/public/v1/bookings'
import { Route as ApiPublicV1LegalRouteImport } from './routes/api/public/v1/legal'
import { Route as ApiPublicV1PaymentDetailsRouteImport } from './routes/api/public/v1/payment-details'
import { Route as ApiPublicV1PropertiesRouteImport } from './routes/api/public/v1/properties'
import { Route as ApiPublicV1QuoteRouteImport } from './routes/api/public/v1/quote'
import { Route as ApiStaffV1RoomsRouteImport } from './routes/api/staff/v1/rooms'
import { Route as EnApartamentaiTipasCategorySlugRouteImport } from './routes/en/apartamentai.tipas.$categorySlug'
import { Route as AuthenticatedAdminPropertiesIdEditRouteImport } from './routes/_authenticated/admin.properties.$id.edit'
import { Route as ApiPublicV1BookingsBookingNumberRouteImport } from './routes/api/public/v1/bookings.$bookingNumber'
import { Route as ApiPublicV1PropertiesIdRouteImport } from './routes/api/public/v1/properties.$id'
import { Route as ApiStaffV1RoomsIdAssignRouteImport } from './routes/api/staff/v1/rooms.$id.assign'
import { Route as ApiStaffV1RoomsIdCommentsRouteImport } from './routes/api/staff/v1/rooms.$id.comments'
import { Route as ApiStaffV1RoomsIdIssueRouteImport } from './routes/api/staff/v1/rooms.$id.issue'
import { Route as ApiStaffV1RoomsIdStatusRouteImport } from './routes/api/staff/v1/rooms.$id.status'
import { Route as ApiStaffV1RoomsIdUnassignRouteImport } from './routes/api/staff/v1/rooms.$id.unassign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiRoute = ApartamentaiRouteImport.update({
  id: '/apartamentai',
  path: '/apartamentai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BanketineSaleRoute = BanketineSaleRouteImport.update({
  id: '/banketine-sale',
  path: '/banketine-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const DovanuKuponaiRoute = DovanuKuponaiRouteImport.update({
  id: '/dovanu-kuponai',
  path: '/dovanu-kuponai',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const NamelisRoute = NamelisRouteImport.update({
  id: '/namelis',
  path: '/namelis',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RestobarasRoute = RestobarasRouteImport.update({
  id: '/restobaras',
  path: '/restobaras',
  getParentRoute: () => rootRouteImport,
} as any)
const SaunaRoute = SaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApartamentaiIndexRoute = ApartamentaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiPropertyIdRoute = ApartamentaiPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiStandartiniaiRoute =
  ApartamentaiStandartiniaiRouteImport.update({
    id: '/standartiniai',
    path: '/standartiniai',
    getParentRoute: () => ApartamentaiRoute,
  } as any)
const ApartamentaiSuTerasaRoute = ApartamentaiSuTerasaRouteImport.update({
  id: '/su-terasa',
  path: '/su-terasa',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApieIndexRoute = ApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApieRoute,
} as any)
const ApieTaisyklesRoute = ApieTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => ApieRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApartamentaiRoute = EnApartamentaiRouteImport.update({
  id: '/apartamentai',
  path: '/apartamentai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApieRoute = EnApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnBanketineSaleRoute = EnBanketineSaleRouteImport.update({
  id: '/banketine-sale',
  path: '/banketine-sale',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnDovanuKuponaiRoute = EnDovanuKuponaiRouteImport.update({
  id: '/dovanu-kuponai',
  path: '/dovanu-kuponai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnKontaktaiRoute = EnKontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnNamelisRoute = EnNamelisRouteImport.update({
  id: '/namelis',
  path: '/namelis',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPrivatumoPolitikaRoute = EnPrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnRestobarasRoute = EnRestobarasRouteImport.update({
  id: '/restobaras',
  path: '/restobaras',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnSaunaRoute = EnSaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnTaisyklesRoute = EnTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnRouteRoute,
} as any)
const RezervacijaPatvirtintaRoute = RezervacijaPatvirtintaRouteImport.update({
  id: '/rezervacija/patvirtinta',
  path: '/rezervacija/patvirtinta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHousekeepingRoute =
  AuthenticatedAdminHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const ApartamentaiTipasCategorySlugRoute =
  ApartamentaiTipasCategorySlugRouteImport.update({
    id: '/tipas/$categorySlug',
    path: '/tipas/$categorySlug',
    getParentRoute: () => ApartamentaiRoute,
  } as any)
const ApiPublicIcalSyncRoute = ApiPublicIcalSyncRouteImport.update({
  id: '/api/public/ical-sync',
  path: '/api/public/ical-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsCronRoute =
  ApiPublicNotificationsCronRouteImport.update({
    id: '/api/public/notifications-cron',
    path: '/api/public/notifications-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnApartamentaiIndexRoute = EnApartamentaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApartamentaiRoute,
} as any)
const EnApartamentaiPropertyIdRoute =
  EnApartamentaiPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)
const EnApartamentaiStandartiniaiRoute =
  EnApartamentaiStandartiniaiRouteImport.update({
    id: '/standartiniai',
    path: '/standartiniai',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)
const EnApartamentaiSuTerasaRoute = EnApartamentaiSuTerasaRouteImport.update({
  id: '/su-terasa',
  path: '/su-terasa',
  getParentRoute: () => EnApartamentaiRoute,
} as any)
const EnApieIndexRoute = EnApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApieRoute,
} as any)
const EnApieTaisyklesRoute = EnApieTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnApieRoute,
} as any)
const EnRezervacijaPatvirtintaRoute =
  EnRezervacijaPatvirtintaRouteImport.update({
    id: '/rezervacija/patvirtinta',
    path: '/rezervacija/patvirtinta',
    getParentRoute: () => EnRouteRoute,
  } as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsNewRoute =
  AuthenticatedAdminBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIndexRoute =
  AuthenticatedAdminPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesNewRoute =
  AuthenticatedAdminPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1AvailabilityRoute = ApiPublicV1AvailabilityRouteImport.update({
  id: '/api/public/v1/availability',
  path: '/api/public/v1/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BookingsRoute = ApiPublicV1BookingsRouteImport.update({
  id: '/api/public/v1/bookings',
  path: '/api/public/v1/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LegalRoute = ApiPublicV1LegalRouteImport.update({
  id: '/api/public/v1/legal',
  path: '/api/public/v1/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PaymentDetailsRoute =
  ApiPublicV1PaymentDetailsRouteImport.update({
    id: '/api/public/v1/payment-details',
    path: '/api/public/v1/payment-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PropertiesRoute = ApiPublicV1PropertiesRouteImport.update({
  id: '/api/public/v1/properties',
  path: '/api/public/v1/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuoteRoute = ApiPublicV1QuoteRouteImport.update({
  id: '/api/public/v1/quote',
  path: '/api/public/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffV1RoomsRoute = ApiStaffV1RoomsRouteImport.update({
  id: '/api/staff/v1/rooms',
  path: '/api/staff/v1/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const EnApartamentaiTipasCategorySlugRoute =
  EnApartamentaiTipasCategorySlugRouteImport.update({
    id: '/tipas/$categorySlug',
    path: '/tipas/$categorySlug',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)
const AuthenticatedAdminPropertiesIdEditRoute =
  AuthenticatedAdminPropertiesIdEditRouteImport.update({
    id: '/properties/$id/edit',
    path: '/properties/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1BookingsBookingNumberRoute =
  ApiPublicV1BookingsBookingNumberRouteImport.update({
    id: '/$bookingNumber',
    path: '/$bookingNumber',
    getParentRoute: () => ApiPublicV1BookingsRoute,
  } as any)
const ApiPublicV1PropertiesIdRoute = ApiPublicV1PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PropertiesRoute,
} as any)
const ApiStaffV1RoomsIdAssignRoute = ApiStaffV1RoomsIdAssignRouteImport.update({
  id: '/$id/assign',
  path: '/$id/assign',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdCommentsRoute =
  ApiStaffV1RoomsIdCommentsRouteImport.update({
    id: '/$id/comments',
    path: '/$id/comments',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)
const ApiStaffV1RoomsIdIssueRoute = ApiStaffV1RoomsIdIssueRouteImport.update({
  id: '/$id/issue',
  path: '/$id/issue',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdStatusRoute = ApiStaffV1RoomsIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdUnassignRoute =
  ApiStaffV1RoomsIdUnassignRouteImport.update({
    id: '/$id/unassign',
    path: '/$id/unassign',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/apartamentai': typeof EnApartamentaiRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/en/apartamentai/': typeof EnApartamentaiIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai': typeof ApartamentaiIndexRoute
  '/apie': typeof ApieIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/en/apartamentai': typeof EnApartamentaiIndexRoute
  '/en/apie': typeof EnApieIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/kontaktai': typeof KontaktaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/apartamentai': typeof EnApartamentaiRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/en/apartamentai/': typeof EnApartamentaiIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/_authenticated/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/_authenticated/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/apartamentai'
    | '/apie'
    | '/auth'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/reset-password'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/admin'
    | '/staff'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/apartamentai'
    | '/en/apie'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/kontaktai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/en/'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/settings'
    | '/staff/$id'
    | '/apartamentai/tipas/$categorySlug'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/admin/'
    | '/staff/'
    | '/en/apartamentai/'
    | '/en/apie/'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/apartamentai/tipas/$categorySlug'
    | '/admin/bookings/'
    | '/admin/properties/'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/reset-password'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/kontaktai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai'
    | '/apie'
    | '/en'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/settings'
    | '/staff/$id'
    | '/apartamentai/tipas/$categorySlug'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/admin'
    | '/staff'
    | '/en/apartamentai'
    | '/en/apie'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/apartamentai/tipas/$categorySlug'
    | '/admin/bookings'
    | '/admin/properties'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/en'
    | '/apartamentai'
    | '/apie'
    | '/auth'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/kontaktai'
    | '/namelis'
    | '/privatumo-politika'
    | '/reset-password'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/apartamentai'
    | '/en/apie'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/kontaktai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/en/'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/housekeeping'
    | '/_authenticated/admin/settings'
    | '/_authenticated/staff/$id'
    | '/apartamentai/tipas/$categorySlug'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/en/apartamentai/'
    | '/en/apie/'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/admin/bookings/new'
    | '/_authenticated/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/apartamentai/tipas/$categorySlug'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/admin/properties/'
    | '/_authenticated/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ApartamentaiRoute: typeof ApartamentaiRouteWithChildren
  ApieRoute: typeof ApieRouteWithChildren
  AuthRoute: typeof AuthRoute
  BanketineSaleRoute: typeof BanketineSaleRoute
  DovanuKuponaiRoute: typeof DovanuKuponaiRoute
  KontaktaiRoute: typeof KontaktaiRoute
  NamelisRoute: typeof NamelisRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestobarasRoute: typeof RestobarasRoute
  SaunaRoute: typeof SaunaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaisyklesRoute: typeof TaisyklesRoute
  RezervacijaPatvirtintaRoute: typeof RezervacijaPatvirtintaRoute
  ApiPublicIcalSyncRoute: typeof ApiPublicIcalSyncRoute
  ApiPublicNotificationsCronRoute: typeof ApiPublicNotificationsCronRoute
  ApiPublicV1AvailabilityRoute: typeof ApiPublicV1AvailabilityRoute
  ApiPublicV1BookingsRoute: typeof ApiPublicV1BookingsRouteWithChildren
  ApiPublicV1LegalRoute: typeof ApiPublicV1LegalRoute
  ApiPublicV1PaymentDetailsRoute: typeof ApiPublicV1PaymentDetailsRoute
  ApiPublicV1PropertiesRoute: typeof ApiPublicV1PropertiesRouteWithChildren
  ApiPublicV1QuoteRoute: typeof ApiPublicV1QuoteRoute
  ApiStaffV1RoomsRoute: typeof ApiStaffV1RoomsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai': {
      id: '/apartamentai'
      path: '/apartamentai'
      fullPath: '/apartamentai'
      preLoaderRoute: typeof ApartamentaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banketine-sale': {
      id: '/banketine-sale'
      path: '/banketine-sale'
      fullPath: '/banketine-sale'
      preLoaderRoute: typeof BanketineSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovanu-kuponai': {
      id: '/dovanu-kuponai'
      path: '/dovanu-kuponai'
      fullPath: '/dovanu-kuponai'
      preLoaderRoute: typeof DovanuKuponaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namelis': {
      id: '/namelis'
      path: '/namelis'
      fullPath: '/namelis'
      preLoaderRoute: typeof NamelisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restobaras': {
      id: '/restobaras'
      path: '/restobaras'
      fullPath: '/restobaras'
      preLoaderRoute: typeof RestobarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauna': {
      id: '/sauna'
      path: '/sauna'
      fullPath: '/sauna'
      preLoaderRoute: typeof SaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apartamentai/': {
      id: '/apartamentai/'
      path: '/'
      fullPath: '/apartamentai/'
      preLoaderRoute: typeof ApartamentaiIndexRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/$propertyId': {
      id: '/apartamentai/$propertyId'
      path: '/$propertyId'
      fullPath: '/apartamentai/$propertyId'
      preLoaderRoute: typeof ApartamentaiPropertyIdRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/standartiniai': {
      id: '/apartamentai/standartiniai'
      path: '/standartiniai'
      fullPath: '/apartamentai/standartiniai'
      preLoaderRoute: typeof ApartamentaiStandartiniaiRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/su-terasa': {
      id: '/apartamentai/su-terasa'
      path: '/su-terasa'
      fullPath: '/apartamentai/su-terasa'
      preLoaderRoute: typeof ApartamentaiSuTerasaRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apie/': {
      id: '/apie/'
      path: '/'
      fullPath: '/apie/'
      preLoaderRoute: typeof ApieIndexRouteImport
      parentRoute: typeof ApieRoute
    }
    '/apie/taisykles': {
      id: '/apie/taisykles'
      path: '/taisykles'
      fullPath: '/apie/taisykles'
      preLoaderRoute: typeof ApieTaisyklesRouteImport
      parentRoute: typeof ApieRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apartamentai': {
      id: '/en/apartamentai'
      path: '/apartamentai'
      fullPath: '/en/apartamentai'
      preLoaderRoute: typeof EnApartamentaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apie': {
      id: '/en/apie'
      path: '/apie'
      fullPath: '/en/apie'
      preLoaderRoute: typeof EnApieRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/banketine-sale': {
      id: '/en/banketine-sale'
      path: '/banketine-sale'
      fullPath: '/en/banketine-sale'
      preLoaderRoute: typeof EnBanketineSaleRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/dovanu-kuponai': {
      id: '/en/dovanu-kuponai'
      path: '/dovanu-kuponai'
      fullPath: '/en/dovanu-kuponai'
      preLoaderRoute: typeof EnDovanuKuponaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/kontaktai': {
      id: '/en/kontaktai'
      path: '/kontaktai'
      fullPath: '/en/kontaktai'
      preLoaderRoute: typeof EnKontaktaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/namelis': {
      id: '/en/namelis'
      path: '/namelis'
      fullPath: '/en/namelis'
      preLoaderRoute: typeof EnNamelisRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/privatumo-politika': {
      id: '/en/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/en/privatumo-politika'
      preLoaderRoute: typeof EnPrivatumoPolitikaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/restobaras': {
      id: '/en/restobaras'
      path: '/restobaras'
      fullPath: '/en/restobaras'
      preLoaderRoute: typeof EnRestobarasRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/sauna': {
      id: '/en/sauna'
      path: '/sauna'
      fullPath: '/en/sauna'
      preLoaderRoute: typeof EnSaunaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/taisykles': {
      id: '/en/taisykles'
      path: '/taisykles'
      fullPath: '/en/taisykles'
      preLoaderRoute: typeof EnTaisyklesRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/rezervacija/patvirtinta': {
      id: '/rezervacija/patvirtinta'
      path: '/rezervacija/patvirtinta'
      fullPath: '/rezervacija/patvirtinta'
      preLoaderRoute: typeof RezervacijaPatvirtintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/housekeeping': {
      id: '/_authenticated/admin/housekeeping'
      path: '/housekeeping'
      fullPath: '/admin/housekeeping'
      preLoaderRoute: typeof AuthenticatedAdminHousekeepingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/apartamentai/tipas/$categorySlug': {
      id: '/apartamentai/tipas/$categorySlug'
      path: '/tipas/$categorySlug'
      fullPath: '/apartamentai/tipas/$categorySlug'
      preLoaderRoute: typeof ApartamentaiTipasCategorySlugRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/api/public/ical-sync': {
      id: '/api/public/ical-sync'
      path: '/api/public/ical-sync'
      fullPath: '/api/public/ical-sync'
      preLoaderRoute: typeof ApiPublicIcalSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications-cron': {
      id: '/api/public/notifications-cron'
      path: '/api/public/notifications-cron'
      fullPath: '/api/public/notifications-cron'
      preLoaderRoute: typeof ApiPublicNotificationsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/apartamentai/': {
      id: '/en/apartamentai/'
      path: '/'
      fullPath: '/en/apartamentai/'
      preLoaderRoute: typeof EnApartamentaiIndexRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/$propertyId': {
      id: '/en/apartamentai/$propertyId'
      path: '/$propertyId'
      fullPath: '/en/apartamentai/$propertyId'
      preLoaderRoute: typeof EnApartamentaiPropertyIdRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/standartiniai': {
      id: '/en/apartamentai/standartiniai'
      path: '/standartiniai'
      fullPath: '/en/apartamentai/standartiniai'
      preLoaderRoute: typeof EnApartamentaiStandartiniaiRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/su-terasa': {
      id: '/en/apartamentai/su-terasa'
      path: '/su-terasa'
      fullPath: '/en/apartamentai/su-terasa'
      preLoaderRoute: typeof EnApartamentaiSuTerasaRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apie/': {
      id: '/en/apie/'
      path: '/'
      fullPath: '/en/apie/'
      preLoaderRoute: typeof EnApieIndexRouteImport
      parentRoute: typeof EnApieRoute
    }
    '/en/apie/taisykles': {
      id: '/en/apie/taisykles'
      path: '/taisykles'
      fullPath: '/en/apie/taisykles'
      preLoaderRoute: typeof EnApieTaisyklesRouteImport
      parentRoute: typeof EnApieRoute
    }
    '/en/rezervacija/patvirtinta': {
      id: '/en/rezervacija/patvirtinta'
      path: '/rezervacija/patvirtinta'
      fullPath: '/en/rezervacija/patvirtinta'
      preLoaderRoute: typeof EnRezervacijaPatvirtintaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/new': {
      id: '/_authenticated/admin/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AuthenticatedAdminBookingsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/': {
      id: '/_authenticated/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/new': {
      id: '/_authenticated/admin/properties/new'
      path: '/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/availability': {
      id: '/api/public/v1/availability'
      path: '/api/public/v1/availability'
      fullPath: '/api/public/v1/availability'
      preLoaderRoute: typeof ApiPublicV1AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bookings': {
      id: '/api/public/v1/bookings'
      path: '/api/public/v1/bookings'
      fullPath: '/api/public/v1/bookings'
      preLoaderRoute: typeof ApiPublicV1BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/legal': {
      id: '/api/public/v1/legal'
      path: '/api/public/v1/legal'
      fullPath: '/api/public/v1/legal'
      preLoaderRoute: typeof ApiPublicV1LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/payment-details': {
      id: '/api/public/v1/payment-details'
      path: '/api/public/v1/payment-details'
      fullPath: '/api/public/v1/payment-details'
      preLoaderRoute: typeof ApiPublicV1PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/properties': {
      id: '/api/public/v1/properties'
      path: '/api/public/v1/properties'
      fullPath: '/api/public/v1/properties'
      preLoaderRoute: typeof ApiPublicV1PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quote': {
      id: '/api/public/v1/quote'
      path: '/api/public/v1/quote'
      fullPath: '/api/public/v1/quote'
      preLoaderRoute: typeof ApiPublicV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/v1/rooms': {
      id: '/api/staff/v1/rooms'
      path: '/api/staff/v1/rooms'
      fullPath: '/api/staff/v1/rooms'
      preLoaderRoute: typeof ApiStaffV1RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/apartamentai/tipas/$categorySlug': {
      id: '/en/apartamentai/tipas/$categorySlug'
      path: '/tipas/$categorySlug'
      fullPath: '/en/apartamentai/tipas/$categorySlug'
      preLoaderRoute: typeof EnApartamentaiTipasCategorySlugRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/_authenticated/admin/properties/$id/edit': {
      id: '/_authenticated/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/admin/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/bookings/$bookingNumber': {
      id: '/api/public/v1/bookings/$bookingNumber'
      path: '/$bookingNumber'
      fullPath: '/api/public/v1/bookings/$bookingNumber'
      preLoaderRoute: typeof ApiPublicV1BookingsBookingNumberRouteImport
      parentRoute: typeof ApiPublicV1BookingsRoute
    }
    '/api/public/v1/properties/$id': {
      id: '/api/public/v1/properties/$id'
      path: '/$id'
      fullPath: '/api/public/v1/properties/$id'
      preLoaderRoute: typeof ApiPublicV1PropertiesIdRouteImport
      parentRoute: typeof ApiPublicV1PropertiesRoute
    }
    '/api/staff/v1/rooms/$id/assign': {
      id: '/api/staff/v1/rooms/$id/assign'
      path: '/$id/assign'
      fullPath: '/api/staff/v1/rooms/$id/assign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdAssignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/comments': {
      id: '/api/staff/v1/rooms/$id/comments'
      path: '/$id/comments'
      fullPath: '/api/staff/v1/rooms/$id/comments'
      preLoaderRoute: typeof ApiStaffV1RoomsIdCommentsRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/issue': {
      id: '/api/staff/v1/rooms/$id/issue'
      path: '/$id/issue'
      fullPath: '/api/staff/v1/rooms/$id/issue'
      preLoaderRoute: typeof ApiStaffV1RoomsIdIssueRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/status': {
      id: '/api/staff/v1/rooms/$id/status'
      path: '/$id/status'
      fullPath: '/api/staff/v1/rooms/$id/status'
      preLoaderRoute: typeof ApiStaffV1RoomsIdStatusRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/unassign': {
      id: '/api/staff/v1/rooms/$id/unassign'
      path: '/$id/unassign'
      fullPath: '/api/staff/v1/rooms/$id/unassign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdUnassignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminHousekeepingRoute: typeof AuthenticatedAdminHousekeepingRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminBookingsNewRoute: typeof AuthenticatedAdminBookingsNewRoute
  AuthenticatedAdminPropertiesNewRoute: typeof AuthenticatedAdminPropertiesNewRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
  AuthenticatedAdminPropertiesIndexRoute: typeof AuthenticatedAdminPropertiesIndexRoute
  AuthenticatedAdminPropertiesIdEditRoute: typeof AuthenticatedAdminPropertiesIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminHousekeepingRoute: AuthenticatedAdminHousekeepingRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  AuthenticatedAdminBookingsNewRoute: AuthenticatedAdminBookingsNewRoute,
  AuthenticatedAdminPropertiesNewRoute: AuthenticatedAdminPropertiesNewRoute,
  AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
  AuthenticatedAdminPropertiesIndexRoute:
    AuthenticatedAdminPropertiesIndexRoute,
  AuthenticatedAdminPropertiesIdEditRoute:
    AuthenticatedAdminPropertiesIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnApartamentaiRouteChildren {
  EnApartamentaiPropertyIdRoute: typeof EnApartamentaiPropertyIdRoute
  EnApartamentaiStandartiniaiRoute: typeof EnApartamentaiStandartiniaiRoute
  EnApartamentaiSuTerasaRoute: typeof EnApartamentaiSuTerasaRoute
  EnApartamentaiIndexRoute: typeof EnApartamentaiIndexRoute
  EnApartamentaiTipasCategorySlugRoute: typeof EnApartamentaiTipasCategorySlugRoute
}

const EnApartamentaiRouteChildren: EnApartamentaiRouteChildren = {
  EnApartamentaiPropertyIdRoute: EnApartamentaiPropertyIdRoute,
  EnApartamentaiStandartiniaiRoute: EnApartamentaiStandartiniaiRoute,
  EnApartamentaiSuTerasaRoute: EnApartamentaiSuTerasaRoute,
  EnApartamentaiIndexRoute: EnApartamentaiIndexRoute,
  EnApartamentaiTipasCategorySlugRoute: EnApartamentaiTipasCategorySlugRoute,
}

const EnApartamentaiRouteWithChildren = EnApartamentaiRoute._addFileChildren(
  EnApartamentaiRouteChildren,
)

interface EnApieRouteChildren {
  EnApieTaisyklesRoute: typeof EnApieTaisyklesRoute
  EnApieIndexRoute: typeof EnApieIndexRoute
}

const EnApieRouteChildren: EnApieRouteChildren = {
  EnApieTaisyklesRoute: EnApieTaisyklesRoute,
  EnApieIndexRoute: EnApieIndexRoute,
}

const EnApieRouteWithChildren =
  EnApieRoute._addFileChildren(EnApieRouteChildren)

interface EnRouteRouteChildren {
  EnApartamentaiRoute: typeof EnApartamentaiRouteWithChildren
  EnApieRoute: typeof EnApieRouteWithChildren
  EnBanketineSaleRoute: typeof EnBanketineSaleRoute
  EnDovanuKuponaiRoute: typeof EnDovanuKuponaiRoute
  EnKontaktaiRoute: typeof EnKontaktaiRoute
  EnNamelisRoute: typeof EnNamelisRoute
  EnPrivatumoPolitikaRoute: typeof EnPrivatumoPolitikaRoute
  EnRestobarasRoute: typeof EnRestobarasRoute
  EnSaunaRoute: typeof EnSaunaRoute
  EnTaisyklesRoute: typeof EnTaisyklesRoute
  EnIndexRoute: typeof EnIndexRoute
  EnRezervacijaPatvirtintaRoute: typeof EnRezervacijaPatvirtintaRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnApartamentaiRoute: EnApartamentaiRouteWithChildren,
  EnApieRoute: EnApieRouteWithChildren,
  EnBanketineSaleRoute: EnBanketineSaleRoute,
  EnDovanuKuponaiRoute: EnDovanuKuponaiRoute,
  EnKontaktaiRoute: EnKontaktaiRoute,
  EnNamelisRoute: EnNamelisRoute,
  EnPrivatumoPolitikaRoute: EnPrivatumoPolitikaRoute,
  EnRestobarasRoute: EnRestobarasRoute,
  EnSaunaRoute: EnSaunaRoute,
  EnTaisyklesRoute: EnTaisyklesRoute,
  EnIndexRoute: EnIndexRoute,
  EnRezervacijaPatvirtintaRoute: EnRezervacijaPatvirtintaRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ApartamentaiRouteChildren {
  ApartamentaiPropertyIdRoute: typeof ApartamentaiPropertyIdRoute
  ApartamentaiStandartiniaiRoute: typeof ApartamentaiStandartiniaiRoute
  ApartamentaiSuTerasaRoute: typeof ApartamentaiSuTerasaRoute
  ApartamentaiIndexRoute: typeof ApartamentaiIndexRoute
  ApartamentaiTipasCategorySlugRoute: typeof ApartamentaiTipasCategorySlugRoute
}

const ApartamentaiRouteChildren: ApartamentaiRouteChildren = {
  ApartamentaiPropertyIdRoute: ApartamentaiPropertyIdRoute,
  ApartamentaiStandartiniaiRoute: ApartamentaiStandartiniaiRoute,
  ApartamentaiSuTerasaRoute: ApartamentaiSuTerasaRoute,
  ApartamentaiIndexRoute: ApartamentaiIndexRoute,
  ApartamentaiTipasCategorySlugRoute: ApartamentaiTipasCategorySlugRoute,
}

const ApartamentaiRouteWithChildren = ApartamentaiRoute._addFileChildren(
  ApartamentaiRouteChildren,
)

interface ApieRouteChildren {
  ApieTaisyklesRoute: typeof ApieTaisyklesRoute
  ApieIndexRoute: typeof ApieIndexRoute
}

const ApieRouteChildren: ApieRouteChildren = {
  ApieTaisyklesRoute: ApieTaisyklesRoute,
  ApieIndexRoute: ApieIndexRoute,
}

const ApieRouteWithChildren = ApieRoute._addFileChildren(ApieRouteChildren)

interface ApiPublicV1BookingsRouteChildren {
  ApiPublicV1BookingsBookingNumberRoute: typeof ApiPublicV1BookingsBookingNumberRoute
}

const ApiPublicV1BookingsRouteChildren: ApiPublicV1BookingsRouteChildren = {
  ApiPublicV1BookingsBookingNumberRoute: ApiPublicV1BookingsBookingNumberRoute,
}

const ApiPublicV1BookingsRouteWithChildren =
  ApiPublicV1BookingsRoute._addFileChildren(ApiPublicV1BookingsRouteChildren)

interface ApiPublicV1PropertiesRouteChildren {
  ApiPublicV1PropertiesIdRoute: typeof ApiPublicV1PropertiesIdRoute
}

const ApiPublicV1PropertiesRouteChildren: ApiPublicV1PropertiesRouteChildren = {
  ApiPublicV1PropertiesIdRoute: ApiPublicV1PropertiesIdRoute,
}

const ApiPublicV1PropertiesRouteWithChildren =
  ApiPublicV1PropertiesRoute._addFileChildren(
    ApiPublicV1PropertiesRouteChildren,
  )

interface ApiStaffV1RoomsRouteChildren {
  ApiStaffV1RoomsIdAssignRoute: typeof ApiStaffV1RoomsIdAssignRoute
  ApiStaffV1RoomsIdCommentsRoute: typeof ApiStaffV1RoomsIdCommentsRoute
  ApiStaffV1RoomsIdIssueRoute: typeof ApiStaffV1RoomsIdIssueRoute
  ApiStaffV1RoomsIdStatusRoute: typeof ApiStaffV1RoomsIdStatusRoute
  ApiStaffV1RoomsIdUnassignRoute: typeof ApiStaffV1RoomsIdUnassignRoute
}

const ApiStaffV1RoomsRouteChildren: ApiStaffV1RoomsRouteChildren = {
  ApiStaffV1RoomsIdAssignRoute: ApiStaffV1RoomsIdAssignRoute,
  ApiStaffV1RoomsIdCommentsRoute: ApiStaffV1RoomsIdCommentsRoute,
  ApiStaffV1RoomsIdIssueRoute: ApiStaffV1RoomsIdIssueRoute,
  ApiStaffV1RoomsIdStatusRoute: ApiStaffV1RoomsIdStatusRoute,
  ApiStaffV1RoomsIdUnassignRoute: ApiStaffV1RoomsIdUnassignRoute,
}

const ApiStaffV1RoomsRouteWithChildren = ApiStaffV1RoomsRoute._addFileChildren(
  ApiStaffV1RoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  ApartamentaiRoute: ApartamentaiRouteWithChildren,
  ApieRoute: ApieRouteWithChildren,
  AuthRoute: AuthRoute,
  BanketineSaleRoute: BanketineSaleRoute,
  DovanuKuponaiRoute: DovanuKuponaiRoute,
  KontaktaiRoute: KontaktaiRoute,
  NamelisRoute: NamelisRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestobarasRoute: RestobarasRoute,
  SaunaRoute: SaunaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaisyklesRoute: TaisyklesRoute,
  RezervacijaPatvirtintaRoute: RezervacijaPatvirtintaRoute,
  ApiPublicIcalSyncRoute: ApiPublicIcalSyncRoute,
  ApiPublicNotificationsCronRoute: ApiPublicNotificationsCronRoute,
  ApiPublicV1AvailabilityRoute: ApiPublicV1AvailabilityRoute,
  ApiPublicV1BookingsRoute: ApiPublicV1BookingsRouteWithChildren,
  ApiPublicV1LegalRoute: ApiPublicV1LegalRoute,
  ApiPublicV1PaymentDetailsRoute: ApiPublicV1PaymentDetailsRoute,
  ApiPublicV1PropertiesRoute: ApiPublicV1PropertiesRouteWithChildren,
  ApiPublicV1QuoteRoute: ApiPublicV1QuoteRoute,
  ApiStaffV1RoomsRoute: ApiStaffV1RoomsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
